/**
 * Пути RPC REST как в esms-arena-app (`/v1/contexts/users.admin.models.rest/functions/...`).
 * Итоговый URL: `VITE_API_BASE_URL` + путь (например `/rest` + `/v1/contexts/...`).
 */
export const REST_FUNCTIONS_BASE = "/v1/contexts/users.admin.models.rest/functions" as const;

export const REST_FUNCTION_PATHS = {
    getSummaryData: `${REST_FUNCTIONS_BASE}/getSummaryData`,
    getProductionPlan: `${REST_FUNCTIONS_BASE}/getProductionPlan`,
    getProductionPlanMachines: `${REST_FUNCTIONS_BASE}/getProductionPlanMachines`,
    getMaterialOrderPlanStages: `${REST_FUNCTIONS_BASE}/getMaterialOrderPlanStages`,
    composeMaterialOrderLines: `${REST_FUNCTIONS_BASE}/composeMaterialOrderLines`,
    listMaterialOrderPickCandidates: `${REST_FUNCTIONS_BASE}/listMaterialOrderPickCandidates`,
    submitMaterialOrderRequest: `${REST_FUNCTIONS_BASE}/submitMaterialOrderRequest`,
    getMachineMaterialLocation: `${REST_FUNCTIONS_BASE}/getMachineMaterialLocation`,
    reprintRollLabelBySeries: `${REST_FUNCTIONS_BASE}/reprintRollLabelBySeries`,
    listBlockReasons: `${REST_FUNCTIONS_BASE}/listBlockReasons`,
    submitBlockRequest: `${REST_FUNCTIONS_BASE}/submitBlockRequest`,
    startProductionPlanStage: `${REST_FUNCTIONS_BASE}/startProductionPlanStage`,
    pauseProductionPlanStage: `${REST_FUNCTIONS_BASE}/pauseProductionPlanStage`,
    continueProductionPlanStage: `${REST_FUNCTIONS_BASE}/continueProductionPlanStage`,
    getOrderExecution: `${REST_FUNCTIONS_BASE}/getOrderExecution`,
    resolveBarcodeOnStage: `${REST_FUNCTIONS_BASE}/resolveBarcodeOnStage`,
    submitMoveToUnwind: `${REST_FUNCTIONS_BASE}/submitMoveToUnwind`,
    getStageRollRegistry: `${REST_FUNCTIONS_BASE}/getStageRollRegistry`,
    getStageRollPresence: `${REST_FUNCTIONS_BASE}/getStageRollPresence`,
    printOrderExecutionMaterialReturnLabel: `${REST_FUNCTIONS_BASE}/printOrderExecutionMaterialReturnLabel`,
    convertConsumedLengthToWeight: `${REST_FUNCTIONS_BASE}/convertConsumedLengthToWeight`,
    listReturnWarehouses: `${REST_FUNCTIONS_BASE}/listReturnWarehouses`,
    submitPartialReturn: `${REST_FUNCTIONS_BASE}/submitPartialReturn`,
    submitFullWriteOff: `${REST_FUNCTIONS_BASE}/submitFullWriteOff`,
    submitStageLkm: `${REST_FUNCTIONS_BASE}/submitStageLkm`,
    eventReleaseProduction: `${REST_FUNCTIONS_BASE}/eventReleaseProduction`,
    eventRollWriteOff: `${REST_FUNCTIONS_BASE}/eventRollWriteOff`,
    discardEventRoll: `${REST_FUNCTIONS_BASE}/discardEventRoll`,
    acceptRawFromEvent: `${REST_FUNCTIONS_BASE}/acceptRawFromEvent`,
    getReleaseFormInit: `${REST_FUNCTIONS_BASE}/getReleaseFormInit`,
    getBatchReleases: `${REST_FUNCTIONS_BASE}/getBatchReleases`,
    getEventsSummary: `${REST_FUNCTIONS_BASE}/getEventsSummary`,
    getMaterialEventsSummary: `${REST_FUNCTIONS_BASE}/getMaterialEventsSummary`,
    getListMaterialSignal: `${REST_FUNCTIONS_BASE}/getListMaterialSignal`,
    getJbTable: `${REST_FUNCTIONS_BASE}/getJbTable`,
    getLastProcessParamsSlices: `${REST_FUNCTIONS_BASE}/getLastProcessParamsSlices`,
    getProcessControl: `${REST_FUNCTIONS_BASE}/getProcessControl`,
    saveProcessControl: `${REST_FUNCTIONS_BASE}/saveProcessControl`,
    saveManualProcessParams: `${REST_FUNCTIONS_BASE}/saveManualProcessParams`,
    jbPrintSheet2: `${REST_FUNCTIONS_BASE}/jbPrintSheet2`,
    jbPrintSheet1: `${REST_FUNCTIONS_BASE}/jbPrintSheet1`,
    jbPrintSheet3: `${REST_FUNCTIONS_BASE}/jbPrintSheet3`,
    jbMapColorControl: `${REST_FUNCTIONS_BASE}/jbMapColorControl`,
    jbPrintSheet6: `${REST_FUNCTIONS_BASE}/jbPrintSheet6`,
    jbPrintSheet4: `${REST_FUNCTIONS_BASE}/jbPrintSheet4`,
    jbFullPrint: `${REST_FUNCTIONS_BASE}/jbFullPrint`,
    jbProcessControl: `${REST_FUNCTIONS_BASE}/jbProcessControl`,
    registerRelease: `${REST_FUNCTIONS_BASE}/registerRelease`,
    prepareReleaseLabel: `${REST_FUNCTIONS_BASE}/prepareReleaseLabel`,
    getArmExecutionMonitoringSummary: `${REST_FUNCTIONS_BASE}/getArmExecutionMonitoringSummary`,
    getArmExecutionMonitoringRollTables: `${REST_FUNCTIONS_BASE}/getArmExecutionMonitoringRollTables`,
    getArmExecutionMonitoringStageEvents: `${REST_FUNCTIONS_BASE}/getArmExecutionMonitoringStageEvents`,
    getProgress: `${REST_FUNCTIONS_BASE}/getProgress`,
    getUnprocessedSignalsSummary: `${REST_FUNCTIONS_BASE}/getUnprocessedSignalsSummary`,
    listUnprocessedSignals: `${REST_FUNCTIONS_BASE}/listUnprocessedSignals`,
    initProductionEventWizard: `${REST_FUNCTIONS_BASE}/initProductionEventWizard`,
    discardProductionEventSignals: `${REST_FUNCTIONS_BASE}/discardProductionEventSignals`,
    getProductionEventProcessJournal: `${REST_FUNCTIONS_BASE}/getProductionEventProcessJournal`,
    registerProductionEvent: `${REST_FUNCTIONS_BASE}/registerProductionEvent`,
    orderStageCompletionInit: `${REST_FUNCTIONS_BASE}/orderStageCompletionInit`,
    orderStageCompletionSubmit: `${REST_FUNCTIONS_BASE}/orderStageCompletionSubmit`,
    /** MES-профиль и роли после POST /auth (Bearer обязателен). */
    mesUserProfile: `${REST_FUNCTIONS_BASE}/mesUserProfile`,
    /** Окружение клиента: каталог временных файлов (Bearer обязателен). */
    clientGetEnvironment: `${REST_FUNCTIONS_BASE}/clientGetEnvironment`,
} as const;
